
server:
    port: 8765
spring:
    application:
        name: netflix-zuul-api-gateway-server
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8762/eureka
logging:
    level:
        root: INFO
        com.lpras: DEBUG
        org.springframework.cloud: WARN
        com.netflix: WARN
        de.codecentric: WARN
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
